name: Python Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd ./apps/cli
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run unittests
      #   run: cd ./apps/cli && pytest --doctest-modules

      - name: Lint with Black
        run: cd ./apps/cli && python -m black **/*.py --check
